baseURL = "https://josephting.my"
languageCode = "en-us"
title = "Joseph Ting"
theme = "hugo-coder"

[params]
    author = "Joseph Ting"
    info = "Full Stack Web Developer"
    description = "Full Stack Web Developer"
    keywords = "personal,developer"
    hideCredits = true
    hideCopyright = true
    favicon_32 = "/favicon-32x32.png"
    favicon_16 = "/favicon-16x16.png"
    custom_css = ["style.css"]
    commit = "https://github.com/josephting/josephting.my/tree/"

[permalinks]
    blog = "/:year/:month/:title/"
    portfolio = "/portfolio/projects/:title/"

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/josephting"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/josephting/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/josephting/"

[[menu.main]]
    name = "Portfolio"
    weight = 1
    url = "/portfolio/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url = "/blog/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
