[[headers]]
    for = "/css/coder*.css"
    [headers.values]
        Access-Control-Allow-Origin = "*"

[[redirects]]
    from = "https://josephting.netlify.com/*"
    to = "https://josephting.my/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/archive-year/"
    to = "/404.html"
    status = 404
    force = true

[[redirects]]
    from = "/archive-month/"
    to = "/404.html"
    status = 404
    force = true
